[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.30"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
# Exclude certora harnesses that reference missing patched files
ignored_error_codes = [6275]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
